Test automation improvements (#97)
* Problem: warning MSB8028: The intermediate directory (x64\Debug\) contains files shared from another project (Tests_RO.vcxproj).  This can lead to incorrect clean and rebuild behavior.

Solution: explicitly specify `IntDir` to be different for the two test projects

* Problem: both Tests and Tests_RO have REVERSE_ORIENTATION #defined

Solution: do not #define REVERSE_ORIENTATION in Tests.vcxproj

* Run even the reverse-orientation tests in Github Actions

* Problem: TestFromTextFile.cpp(103,15): error C3861: 'EXPECT_LQ': identifier not found

Solution: Use `EXPECT_EQ`, which appears to have been the intention here

* Make it so that tests complete for now, even if it means effectively disabling the orientation-after-offset test when orientation is not reversed